#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ["s3m-example-backend/s3m-example-backend.csproj", "s3m-example-backend/"]
RUN dotnet restore "s3m-example-backend/s3m-example-backend.csproj"
COPY . .
WORKDIR "/src/s3m-example-backend"
RUN dotnet build "s3m-example-backend.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "s3m-example-backend.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "s3m-example-backend.dll"]